version: '3.7'
services:
  bot:
    build: .
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:3.0-alpine
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: pgdata
